package com.example.drea_text_studie.ui.studie

val allWordsList: List<String> = listOf(
    "51674 Wiehl",
    "02262 Wiehl",
    "Auto",
    "Navi",
    "Spotify",
    "Links",
    "Rechts",
    "Strasse",
    "53119 Bonn",
    "Musik",
    "54290 Trier",
    "57462 Olpe",
    "Zuhause",
    "Pink",
    "Lady Gaga",
    "Basel",
    "Berlin",
    "Biggesee",
    "02261",
    "Eminem",
    "Radio",
    "SWR3",
    "WDR 4",
    "RPR1",
    "Tanken",
    "Laden",// 26
    "Italien",
    "51063 Koeln",
    "Max Muster",
    "Jane Doe",
)